"use client";

import { useMemo } from "react";
import { getGroupedPortfolioAssets } from "@/lib/pricing";
import { formatCurrency, formatDate, formatNumber } from "@/lib/utils";
import type { CurrencyCode, FxRates, PortfolioAsset } from "@/types/portfolio";

type PortfolioPositionCardsProps = { assets: PortfolioAsset[]; fxRates: FxRates; baseCurrency: CurrencyCode; filter: string; isRefreshing: boolean; onRemove: (assetId: string) => void };

export default function PortfolioPositionCards({ assets, fxRates, baseCurrency, filter, isRefreshing, onRemove }: PortfolioPositionCardsProps) {
  const groups = useMemo(() => { const normalizedFilter = filter.trim().toLocaleLowerCase("pl-PL"); return getGroupedPortfolioAssets(assets, fxRates, baseCurrency).filter((group) => !normalizedFilter || `${group.name} ${group.symbol}`.toLocaleLowerCase("pl-PL").includes(normalizedFilter)).sort((left, right) => right.totalValue - left.totalValue); }, [assets, baseCurrency, filter, fxRates]);
  return <section className="workspace-position-cards" aria-label="Bieżące pozycje — widok mobilny"><div className="workspace-position-filter"><span>Bieżące pozycje</span>{isRefreshing ? <small>Aktualizowanie kursów…</small> : <small>{groups.length} pozycji</small>}</div>{groups.length === 0 ? <p className="workspace-empty-state">Nie ma pozycji pasujących do tego widoku.</p> : null}{groups.map((group) => <article className="workspace-position-card" key={group.key}><header><div><strong>{group.name}</strong><span>{group.symbol} · {group.kind.toUpperCase()}</span></div><strong className={group.profitLossBase >= 0 ? "tone-positive" : "tone-negative"}>{formatCurrency(group.profitLossBase, baseCurrency)}</strong></header><dl><div><dt>Ilość</dt><dd>{formatNumber(group.quantity, group.kind === "crypto" ? 12 : 6)}</dd></div><div><dt>Kurs jednostkowy</dt><dd>{group.currentUnitPrice ? formatCurrency(group.currentUnitPrice, group.marketCurrency) : "Brak kursu"}</dd></div><div><dt>Wartość</dt><dd>{formatCurrency(group.marketValueBase, baseCurrency)}</dd></div><div><dt>Notowanie</dt><dd>{group.latestPriceDate ? formatDate(group.latestPriceDate) : "Do odświeżenia"}</dd></div></dl><details><summary>Więcej informacji</summary><p>Średni zakup: <strong>{formatCurrency(group.averagePurchasePrice, group.averagePurchasePriceCurrency)}</strong></p><p>Wartość w walucie notowania: <strong>{group.marketValueQuote !== undefined ? formatCurrency(group.marketValueQuote, group.marketCurrency) : "Brak kursu"}</strong></p><div className="workspace-position-lots">{group.lots.map((lot) => <div key={lot.id}><span>{formatDate(lot.purchaseDate)} · {formatNumber(lot.quantity, lot.kind === "crypto" ? 12 : 6)}</span><button type="button" onClick={() => onRemove(lot.id)} aria-label={`Usuń lot ${lot.symbol}`}>Usuń</button></div>)}</div></details></article>)}</section>;
}
